export function translate_main_subject(main_subject: string = "") {
  const subjecttype_lookup: Record<string, string[]> = {
    "all": ["all", "all"],
    "random": ["all", "all"],
    "--- all": ["all", "all"],
    "------all": ["all", "all"],
    "------ all": ["all", "all"],

    "object - all": ["object", "all"],
    "--- object - all": ["object", "all"],
    "object": ["object", "all"],
    "object - generic": ["object", "all"],
    "generic object": ["object", "generic objects"],
    "generic objects": ["object", "generic objects"],
    "genericobject": ["object", "generic objects"],
    "genericobjects": ["object", "generic objects"],
    "object - vehicle": ["object", "vehicles"],
    "vehicle": ["object", "vehicles"],
    "vehicles": ["object", "vehicles"],
    "object - food": ["object", "food"],
    "food": ["object", "food"],
    "object - building": ["object", "buildings"],
    "building": ["object", "buildings"],
    "buildings": ["object", "buildings"],
    "object - space": ["object", "space"],
    "space": ["object", "space"],
    "object - flora": ["object", "flora"],
    "flora": ["object", "flora"],
    "nature": ["object", "flora"],

    "animal - all": ["animal", "all"],
    "--- animal - all": ["animal", "all"],
    "animal": ["animal", "all"],
    "animals": ["animal", "all"],
    "animal - generic": ["animal", "generic animal"],
    "generic animal": ["animal", "generic animal"],
    "generic animals": ["animal", "generic animal"],
    "genericanimal": ["animal", "generic animal"],
    "genericanimals": ["animal", "generic animal"],
    "animal - cat": ["animal", "cat"],
    "cat": ["animal", "cat"],
    "cats": ["animal", "cat"],
    "animal - dog": ["animal", "dog"],
    "dog": ["animal", "dog"],
    "dogs": ["animal", "dog"],
    "animal - bird": ["animal", "bird"],
    "bird": ["animal", "bird"],
    "birds": ["animal", "bird"],
    "animal - insect": ["animal", "insect"],
    "insect": ["animal", "insect"],
    "insects": ["animal", "insect"],
    "animal - pokémon": ["animal", "pokemon"],
    "animal - pokemon": ["animal", "pokemon"],
    "pokemon": ["animal", "pokemon"],
    "pokemons": ["animal", "pokemon"],
    "pokémon": ["animal", "pokemon"],
    "pokémons": ["animal", "pokemon"],
    "animal - marine life": ["animal", "marine life"],
    "marine life": ["animal", "marine life"],
    "marinelife": ["animal", "marine life"],
    "ocean gang": ["animal", "marine life"],
    "oceangang": ["animal", "marine life"],
    "marine": ["animal", "marine life"],

    "human - all": ["humanoid", "all"],
    "--- human - all": ["humanoid", "all"],
    "human": ["humanoid", "all"],
    "humans": ["humanoid", "all"],
    "person": ["humanoid", "all"],
    "persons": ["humanoid", "all"],
    "people": ["humanoid", "all"],
    "man": ["humanoid", "all"],
    "woman": ["humanoid", "all"],
    "male": ["humanoid", "all"],
    "female": ["humanoid", "all"],
    "guy": ["humanoid", "all"],
    "girl": ["humanoid", "all"],
    "human - generic": ["humanoid", "human"],
    "generic human": ["humanoid", "human"],
    "generic humans": ["humanoid", "human"],
    "generichuman": ["humanoid", "human"],
    "generichumans": ["humanoid", "human"],
    "human - relations": ["humanoid","manwomanrelation"],
    "relations": ["humanoid","manwomanrelation"],
    "human relations": ["humanoid","manwomanrelation"],
    "humanrelations": ["humanoid","manwomanrelation"],
    "human - celebrity": ["humanoid","non fictional"],
    "celebrities": ["humanoid","non fictional"],
    "celebrity": ["humanoid","non fictional"],
    "human - fictional": ["humanoid","fictional"],
    "fictional characters": ["humanoid","fictional"],
    "fictional character": ["humanoid","fictional"],
    "fictionalcharacters": ["humanoid","fictional"],
    "fictionalcharacter": ["humanoid","fictional"],
    "fictional": ["humanoid","fictional"],
    "human - humanoids": ["humanoid","humanoid"],
    "humanoid": ["humanoid","humanoid"],
    "humanoids": ["humanoid","humanoid"],
    "human - job/title": ["humanoid","job"],
    "job": ["humanoid","job"],
    "jobs": ["humanoid","job"],
    "title": ["humanoid","job"],
    "titles": ["humanoid","job"],
    "human - first name": ["humanoid","firstname"],
    "first name": ["humanoid","firstname"],
    "firstname": ["humanoid","firstname"],
    "human - multiple": ["humanoid","manwomanmultiple"], 
    "multiplehumans": ["humanoid","manwomanmultiple"], 
    "multiple": ["humanoid","manwomanmultiple"], 

    "landscape - all": ["landscape","all"],
    "--- landscape - all": ["landscape","all"],
    "landscape": ["landscape","all"],
    "landscapes": ["landscape","all"],
    "landscape - generic": ["landscape","location"],
    "landscape generic": ["landscape","location"],
    "landscapes generic": ["landscape","location"],
    "landscapegeneric": ["landscape","location"],
    "landscapesgeneric": ["landscape","location"],
    "genericlandscape": ["landscape","location"],
    "generic landscape": ["landscape","location"],
    "genericlandscapes": ["landscape","location"],
    "generic landscapes": ["landscape","location"],
    "landscape - fantasy": ["landscape","fantasy location"],
    "landscape fantasy": ["landscape","fantasy location"],
    "landscapefantasy": ["landscape","fantasy location"],
    "fantasylandscape": ["landscape","fantasy location"],
    "fantasy landscape": ["landscape","fantasy location"],
    "landscape - videogame": ["landscape","videogame location"],
    "landscape videogame": ["landscape","videogame location"],
    "landscapevideogame": ["landscape","videogame location"],
    "videogamelandscape": ["landscape","videogame location"],
    "videogame landscape": ["landscape","videogame location"],
    "landscape - sci-fi": ["landscape","sci-fi location"],
    "landscape sci-fi": ["landscape","sci-fi location"],
    "landscapesci-fi": ["landscape","sci-fi location"],
    "sci-filandscape": ["landscape","sci-fi location"],
    "sci-fi landscape": ["landscape","sci-fi location"],
    "landscape - scifi": ["landscape","sci-fi location"],
    "landscape scifi": ["landscape","sci-fi location"],
    "landscapescifi": ["landscape","sci-fi location"],
    "scifilandscape": ["landscape","sci-fi location"],
    "scifi landscape": ["landscape","sci-fi location"],
    "landscape - biome": ["landscape","biome"],
    "landscape biome": ["landscape","biome"],
    "landscapebiome": ["landscape","biome"],
    "biomelandscape": ["landscape","biome"],
    "biome landscape": ["landscape","biome"],
    "biome": ["landscape","biome"],
    "biomes": ["landscape","biome"],
    "landscape - city": ["landscape","city"],
    "landscape city": ["landscape","city"],
    "landscapecity": ["landscape","city"],
    "citylandscape": ["landscape","city"],
    "city landscape": ["landscape","city"],
    "city": ["landscape","city"],
    "cities": ["landscape","city"],

    "concept - all": ["concept", "all"],
    "--- concept - all": ["concept", "all"],
    "concept": ["concept", "all"],
    "concepts": ["concept", "all"],
    "concept - event": ["concept", "event"],
    "event": ["concept", "event"],
    "events": ["concept", "event"],
    "concept - the x of y": ["concept", "concept"],
    "xofy": ["concept", "concept"],
    "thexofy": ["concept", "concept"],
    "concept - poem lines": ["concept", "poemline"],
    "poem": ["concept", "poemline"],
    "poems": ["concept", "poemline"],
    "poemline": ["concept", "poemline"],
    "poemlines": ["concept", "poemline"],
    "concept - song lines": ["concept", "songline"],
    "song": ["concept", "songline"],
    "songs": ["concept", "songline"],
    "songline": ["concept", "songline"],
    "songlines": ["concept", "songline"],
    "concept - card names": ["concept", "cardname"],
    "cards": ["concept", "cardname"],
    "card": ["concept", "cardname"],
    "cardgame": ["concept", "cardname"],
    "cardgames": ["concept", "cardname"],
    "cardname": ["concept", "cardname"],
    "cardnames": ["concept", "cardname"],
    "concept - episode titles": ["concept", "episodetitle"],
    "episode": ["concept", "episodetitle"],
    "episodes": ["concept", "episodetitle"],
    "episodetitle": ["concept", "episodetitle"],
    "episodetitles": ["concept", "episodetitle"],
    "tv": ["concept", "episodetitle"],
    "tv shows": ["concept", "episodetitle"],
    "tvshows": ["concept", "episodetitle"],
    "concept - mixer": ["concept", "conceptmixer"],
    "concept mixer": ["concept", "conceptmixer"],
    "conceptmixer": ["concept", "conceptmixer"],
    "mixer": ["concept", "conceptmixer"],
  };

  const subjecttype = subjecttype_lookup[main_subject] ?? ["all", "all"];

  return subjecttype;
}

    